version: '3.8'
services:
  stat-server:
    build: stat\stat-server
    container_name: stat-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: stat
    ports:
      - "6541:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stat

  main-service:
    build: main-service
    container_name: main-server
    depends_on:
      - main-db
    ports:
      - "8080:8080"

  main-db:
    image: postgres:14-alpine
    container_name: main-db

