CREATE TABLE IF NOT EXISTS stats
(
    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    income_date     TIMESTAMP WITHOUT TIME ZONE,
    uri VARCHAR(100),
    ip VARCHAR(12),
    app VARCHAR(50)
);
